local servers = {
    ["angularls"] = require("lspmanager.servers.angularls"),
    ["bashls"] = require("lspmanager.servers.bashls"),
    ["clangd"] = require("lspmanager.servers.clangd"),
    ["cmake"] = require("lspmanager.servers.cmake"),
    ["cssls"] = require("lspmanager.servers.cssls"),
    ["dockerls"] = require("lspmanager.servers.dockerls"),
    ["fsautocomplete"] = require("lspmanager.servers.fsautocomplete"),
    ["html"] = require("lspmanager.servers.html"),
    -- ["jdtls"] = require("lspmanager.servers.jdtls"),
    ["jsonls"] = require("lspmanager.servers.jsonls"),
    ["kotlinls"] = require("lspmanager.servers.kotlinls"),
    ["omnisharp"] = require("lspmanager.servers.omnisharp"),
    ["pyright"] = require("lspmanager.servers.pyright"),
    ["rust_analyzer"] = require("lspmanager.servers.rust_analyzer"),
    ["sumneko_lua"] = require("lspmanager.servers.sumneko_lua"),
    ["svelte"] = require("lspmanager.servers.svelte"),
    ["tailwindcss"] = require("lspmanager.servers.tailwindcss"),
    ["terraformls"] = require("lspmanager.servers.terraformls"),
    ["tsserver"] = require("lspmanager.servers.tsserver"),
    ["vimls"] = require("lspmanager.servers.vimls"),
    ["vuels"] = require("lspmanager.servers.vuels"),
}

return servers
